### ISSUE TITLE
Why is my Nearley grammar causing a loop?

### ISSUE THREAD

**Issue by mspoulsen** [kach/nearley#443]
I have posted on stackoverflow:
https://stackoverflow.com/questions/56670020/why-is-my-nearley-grammar-causing-a-loop

Maybe someone here can help? :slightly_smiling_face:

**Comment by tjvr** [comment]
So I'm looking at these two rules:
```ne
composition -> composition _ "," _ expression
```

```ne
expression -> _ rank _
```
And I'm suspicious about how we expand them:
```ne
composition -> composition _ "," _ (_ rank _)
```
We now have two `_` rules next to each other (`_ _`), which isn't good: it means that our grammar is ambiguous, since there are two ways to parse it.

There might be other problems but that's the first thing I can spot.

I'm not sure what you mean by "causes a loop" 🙂

**Comment by mspoulsen** [comment]
I see. Thank you very much. I am slowly learning the small gotchas here and there.
What I meant by causing a loop is that I got the "Possible infinite loop" error on the playground and using nearley-test I could see that the parse table exceed 20k rows, so something was wrong.

Thanks again!
