### ISSUE TITLE
Unpredictable parsing times

### ISSUE THREAD

**Issue by idokutela** [kach/nearley#462]
I don't know if this is really an issue, or just a question.

I'm having trouble with performance parsing a rather complicated grammar that has infix operators.

I made a simple test case that isolates the issue:

```
# Grammar 1
level1 -> 
    _ level1 _ "1" _ level0 _ 
  |  _ level0 _

level0 -> "0"

_ -> " " :*
```

It slows down exponentially, asking it to parse "0 1 0 1 0 ...". On my system, it takes around 2 seconds for a string with twenty 1's, six seconds for twenty-one 1's, and crashes with 22 (apparently with GC issues).

Minor changes to the grammar make it fast. Here are two equivalent grammars (in the sense that they recognise the same strings):

```
# Grammar 2
expr -> _ level1 _

level1 -> 
    level1 _ "1" _ level0 
  | level0

level0 -> "0"

_ -> " " :*
```

```
# Grammar 3
level1 -> _ level0 (_ "1" _ level0):* _
level0 -> "0"
_ -> " " :*
```

I tested both out to 5000 1's. Both slow down, of course, but neither display the catastrophic exponential blow up of "Grammar 1". Instead, they seem to slow down linearly, with a very small constant, Grammar 2 never taking more than 70ms for 5000 1's on my machine, and Grammar 3 about 250ms for the same task.

Is such a dramatic difference in performance expected behaviour? Or is it a bug?

If it's expected, what causes the parser to blow up? Are there general things to avoid or to attempt to help nearley parse quickly?

Some more information that may be relevant:
I first suspected memory issues, and simply postprocessed all rules with `() => null`. Unfortunately, that didn't change anything.

**Comment by kach** [comment]
It's expected — in particular, it's the issue of ambiguity in whitespace. In Grammar 1 a level0 can be either `"0"` or `"_0"` or `"0_"` or `"_0_"` and so on (`_` denoting spaces). A level1 then additionally allows for whitespace. So if I give you `"1_0_1"` it can be parsed as `"1_(0)_1"` or `"1(_0)_1"` or `"1(_0_)1"` or `"1_(0_)1"`. That's 4 options. If I give you 1 0 1 0 1 then that's 4x4 = 16 options… you can see how this becomes exponential quickly. Grammars 2 and 3 don't have this issue because the whitespace is unambiguously just in level1.

**Comment by idokutela** [comment]
Oh, I understand. Bah: grammaring can be tricky!

Thank you for the rapid answer.

As far as I'm concerned, the issue is closed. I'll leave you to make that call though.

PS An irrelevant side remark: I find nearley a delight. Thank you (and to all other contributors).

**Comment by kach** [comment]
Thank you for the kind words!
