### ISSUE TITLE
Let me be honest: `DOCUMENTS SUCKS`

### ISSUE THREAD

**Issue by P0oOOOo0YA** [kach/nearley#490]
I don't know you guys but i can't get my head around the docs. This is another example of great project without a manual. You should be a core maintainer of  the lib  to be able to make sense of the so-called docs.

**Comment by woojoo666** [comment]
I thought the documentation was plenty fine. Perhaps you can give more specific details on where you are confused, and suggest improvements if you have any. This is an open-source project, try to be more constructive than just shouting "DOCUMENTS SUCKS"

**Comment by brucou** [comment]
The documentation is indeed great but it can be improved. I just started using nearley after trying Chevrotain (which does have a great documentation). I picked nearley mostly because I had an issue with Chevrotain playground which the maintainer was unwilling to fix, and the nearley's playground is a joy. 

What I stumbled on is syntax:
- you should group clauses in ( ) before applying the modifiers +, * etc.
- literals are between "
- etc.

Most of the stuff I stumbled upon is actually in the doc. However you need to read a bunch of it, which do not make sense at the moment when you are reading it, so you forget the details of it by the moment you implement something. 

My recommendations is to rework the content of `More syntax: tips and tricks` section:
- comments, charsets and EBNF sections you will need to know most if not all the time for any non-trivial grammar
- the rest : macros, additional js, importing grammars could go to an advanced section, except for big languages (which beginners won't write) I don't see a use.

The `Getting started` section is pretty good, not too much to say there. The `using a parser ` section is not bad, but same remark, it would benefit from separating the advanced content from the most frequently used content.

Also the playground should be put front and center. If not on the doc site, at least in the tutorial tell the user to go try it or include screenshots. That is the most valuable tool for beginners.

Hope this helps.
