### ISSUE TITLE
Question about activity

### ISSUE THREAD

**Issue by bandaloo** [kach/nearley#557]
Firstly, I wanna say thanks for this great package.

I switched from PEGjs because nearley has 10x better documentation and it also seems to be the only javascript PEG parser that plays nice with tokenizers. The typescript postprocessor is an added bonus too! Another reason I switched was that PEGjs hasn't had a release since 2016, and all the pull requests are pretty stale too.

I'm using nearley for my thesis; I am creating a DSL for post-processing effects, building off of the work I've done with [merge-pass](https://github.com/bandaloo/merge-pass). I'm happy to help contribute, although I don't exactly have a PhD in parsers and PLs so my ability to do that probably depends on whether I'm able to seek advice from the core maintainers. The javascript PEG parser generator scene is somewhat bleak other than nearley, so I'm eager to do what I can to help it develop.

Whether this project is super active doesn't really change my decision to use nearley; it still serves my needs the best. I'm just wondering what kind of support I can expect nearley to receive over the months that I'll be depending on it. Thanks again for the great work!

**Comment by kach** [comment]
Hi Cole - thanks for the kind words. Exciting to see nearley used in your thesis - I'd love to read it when you're done!

In terms of support: look, it seems like you're a college senior, and I am too, so you can imagine just about how much free time I have! :) I probably will not have time to help you debug anything 1:1 in detail. However, if you ever have any questions, you are welcome to email me and we can set up a time to talk.

You also mention "contributions" — do you intend to hack on nearley itself, e.g. submit a PR? If so, know that I've generally been open to merging thoughtful PRs as long as they aren't too "invasive" to the codebase, and as long as they are fully backwards-compatible and don't seem to introduce any new bugs. My first duty is to current users of nearley — don't want to break anything for them! — but after that I would be very happy to support you in turning your thesis work into something used by real people in the real world! The most important thing is to discuss your planned changes with me ahead of time so that we're not in a situation where you do a lot of work that ultimately doesn't get merged.

Did that help?

**Comment by bandaloo** [comment]
@kach Great! That answers my questions; I'll close the issue. We'll see how much I actually need to hack at nearley and if that amounts to a PR that would be cool. I can share more of the work I'm doing with nearley once it's more than a couple of tests and vaporware. Best of luck with college!
